### ISSUE TITLE
Convert to promises

### ISSUE THREAD

**Issue by tomvlk** [tomvlk/node-split-file#11]
I think it would be nice to provide the 2.x versions with promises (callback + promise or promise only?). This will not only improve the compatibility with ES2015 styles, but also the integrations for the upcoming `async await` syntax.

@purplecones How is your opinion about this, and related to your projects environment/integrations.

**Comment by purplecones** [comment]
I'm all for using the new async/await functionality. It's so much cleaner. We're currently doing it that way for our [project](https://github.com/jkrup/meteor-now/blob/master/src/app.js#L34-L46) by wrapping `split-file` with a promise and using async/await until its done.

**Comment by tomvlk** [comment]
@purplecones Okay, nice :smiley:. I really love the new style too. Let's plan this for one of the next alpha releases, make sure you stick with alpha1 for now. :lock:

**Comment by tomvlk** [comment]
For the first implementation see f270cef921deca104589625503716f29cec01b71. Only did basic testing.

**Comment by tomvlk** [comment]
@purplecones `2.0.0-beta.1` has been released with Promises (using bluebird for compatibility and integration).
