### ISSUE TITLE
Out of memory when splitting file that is bigger than 500mb

### ISSUE THREAD

**Issue by aleksandar-b** [tomvlk/node-split-file#15]
Node gives me this error
`FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory`

I split large file, then sequently upload them one by one.

**Comment by tomvlk** [comment]
Due to the default memory limit in NodeJS it's not possible to split large files that couldn't use the benefits of streamed reading/writing.
You could try to split it in more parts, maybe this works? What command is executed exactly and what sort of file?

**Comment by aleksandar-b** [comment]
tnx, I resolved it. I think it was issue with bluebird, not with this module. But I have another serious issue.
