### ISSUE TITLE
.splitFileBySize()  not working

### ISSUE THREAD

**Issue by aleksandar-b** [tomvlk/node-split-file#16]
`ReferenceError: parts is not defined`
In module there is a line which I think is the problem

```
SplitFile.prototype.splitFileBySize = function(file, maxSize) {
    var self = this;
    
    // Validate parameters.
    if (parts < 1) {
        return Promise.reject(new Error("Parameter 'parts' is invalid, must contain an integer value."));
    }
```

parts is not defined because it does not receive any parameter `parts` just  `file` and `maxSize`.

**Comment by aleksandar-b** [comment]
The function does not need to validate parts. I just deleted that line and it works.

**Comment by tomvlk** [comment]
Okay, nice catch, you can open a PR for this, just remove it indeed.
