### ISSUE TITLE
splitFile and splitFileBySize return empty object

### ISSUE THREAD

**Issue by shazgames1** [tomvlk/node-split-file#35]
Doesn't work on node v14

**Comment by tomvlk** [comment]
@shazgames Could you please elaborate on the issue you have with Node v14? Is it the CLI or the API? Please provide a code snippet if possible.

**Comment by shazgames1** [comment]
I used api from code. Code like this:
```
const splitFile = require('split-file');

splitFile.splitFile('./kek.png', 2)
  .then((names) => {
    console.log(names);
  })
  .catch((err) => {
    console.log('Error: ', err);
  });
```
doesn't return any errors but returns empty object
