### ISSUE TITLE
Splitting XLXS filetype

### ISSUE THREAD

**Issue by adityabajpai** [tomvlk/node-split-file#36]
When trying to split CheckDetails.xlxs file then generating a file like CheckDetails.xlxs.sf-part01 and so on and when trying to rewrite new xlxs file from the generated file then not able to get back the original file, in fact, getting empty xlsx file

**Comment by tomvlk** [comment]
Are you able to provide the file, or a similar file that corrupts? How are you merging the file exactly?

**Comment by adityabajpai** [comment]
I am not merging the file I just trying to read the the data from the splitted files
You can have a look below which give you better understandig regarding my issue

const splitFile = require('split-file');
 
splitFile.splitFile('./ClaimsDetails.xlsx', 10)
  .then((names) => {
    console.log(names);
  })
  .catch((err) => {
    console.log('Error: ', err);
  });
I am trying this and getting split file as
ClaimsDetails.xlsx.sf-part01
...
...
ClaimsDetails.xlsx.sf-part10
and now when I am using ClaimsDetails.xlsx.sf-part01 to get data back I am gettting empty file

**Comment by tomvlk** [comment]
How are you reading the split file exactly?

**Comment by adityabajpai** [comment]
As I have split the xlxs file so I am supposing that I am getting a split file of xlxs type so I am reading the split file using xlxs node module

**Comment by tomvlk** [comment]
You can not read the splitted files, they are non readable in their format.
